on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows Release
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Windows)
        
        run: |
          choco install -y .github/workflows/choco_packages.config
          curl -L https://github.com/libusb/libusb/releases/download/v1.0.27/libusb-1.0.27.7z -o libusb.7z
          7z x libusb.7z -olibusb
      - name: Set LIBUSB_ROOT (Windows)
        
        shell: bash
        run: echo "LIBUSB_ROOT=$(pwd)/libusb" >> "$GITHUB_ENV"

      - name: Checkout Pico SDK
        uses: actions/checkout@v4
        with:
          repository: raspberrypi/pico-sdk
          ref: develop
          path: pico-sdk
          submodules: recursive

      - name: Verify submodules
        run: |
          git -C pico-sdk submodule status
          git submodule status

      - name: Build and Install
        run: |
          cmake -S . -B build -G "Ninja" -D PICO_SDK_PATH="${{ github.workspace }}/pico-sdk" -D USE_PRECOMPILED=false
          cmake --build build
          
      - name: Add to path (Windows)
        if: runner.os == 'Windows'
        run: echo "C:\Program Files (x86)\picotool\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Test
        run: |
          picotool help
          curl -L https://datasheets.raspberrypi.com/soft/blink.uf2 -o blink.uf2
          curl -L https://datasheets.raspberrypi.com/soft/hello_world.uf2 -o hello_world.uf2
          curl -L https://datasheets.raspberrypi.com/soft/flash_nuke.uf2 -o flash_nuke.uf2
          picotool info -a blink.uf2
          picotool info -a hello_world.uf2
          picotool info -a flash_nuke.uf2

      - name: Create release assets
        run: |
          mkdir release
          copy build\picotool.exe release\
          7z a release/picotool.zip release/picotool.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: release/picotool.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
